/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package profilegen;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author DXNNX
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlblpanel = new javax.swing.JPanel();
        mainmenu = new javax.swing.JLabel();
        addprofile = new javax.swing.JButton();
        profiles = new javax.swing.JButton();
        editprofile = new javax.swing.JButton();
        endprofile = new javax.swing.JButton();
        addpelea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Manager v1.0");
        setFocusable(false);

        mainmenu.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        mainmenu.setText("Menu Principal");

        javax.swing.GroupLayout mainlblpanelLayout = new javax.swing.GroupLayout(mainlblpanel);
        mainlblpanel.setLayout(mainlblpanelLayout);
        mainlblpanelLayout.setHorizontalGroup(
            mainlblpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainlblpanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mainmenu)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainlblpanelLayout.setVerticalGroup(
            mainlblpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainlblpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainmenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addprofile.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        addprofile.setText("Agregar Perfil");
        addprofile.setFocusable(false);
        addprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprofileActionPerformed(evt);
            }
        });

        profiles.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        profiles.setText("Perfiles");
        profiles.setFocusable(false);
        profiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilesActionPerformed(evt);
            }
        });

        editprofile.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        editprofile.setText("Modificar Perfil");
        editprofile.setFocusable(false);
        editprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileActionPerformed(evt);
            }
        });

        endprofile.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        endprofile.setText("Clausurar Perfil");
        endprofile.setFocusable(false);

        addpelea.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        addpelea.setText("Agregar Pelea");
        addpelea.setFocusable(false);
        addpelea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpeleaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endprofile, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
            .addComponent(profiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addprofile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
            .addComponent(addpelea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(mainlblpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainlblpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(profiles, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addpelea, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileActionPerformed
                String line;
                String nombre = "";
                String dia = "";
                String mes = "";
                String year = "";
                String madre = "";
                String padre = "";
                String nacionalidad = "";
                String genero = "";
                String foto = "";
                String win = "";
                String same = "";
                String lose = "";
                String id = "";
                String nota ="";
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File("./database/animales"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()))) {

                
                
                
                int count =0;
                while ((line = br.readLine()) != null) {
                    if (count==0){
                        nombre=line;
                    }else if (count==1){
                        dia=line;
                    }else if (count==2){
                        mes=line;
                    }else if (count==3){
                        year=line;
                    }else if (count==4){
                        madre=line;
                    }else if (count==5){
                        padre=line;
                    }else if (count==6){
                        nacionalidad=line;
                    }else if (count==7){
                        genero=line;
                    }else if (count==8){
                        foto=line;
                    }else if (count==9){
                        win=line;
                    }else if (count==10){
                        same=line;
                    }else if (count==11){
                        lose=line;
                    }else if (count==12){
                        id=line;
                    }else{
                        nota=nota+line+"\n";
                    }
                    count++;
                }      try {
                    br.close();
                    editar calc = new editar();
                    calc.newwindow(nombre, dia, mes, year, madre, padre, nacionalidad, genero, foto, win, same, lose, id,nota);
                    calc.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    
    }//GEN-LAST:event_editprofileActionPerformed

    private void addprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprofileActionPerformed
addform nuevo = new addform();
nuevo.setVisible(true);
    }//GEN-LAST:event_addprofileActionPerformed

    private void addpeleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpeleaActionPerformed
                String line;
                String nombre = "";
                String dia = "";
                String mes = "";
                String year = "";
                String madre = "";
                String padre = "";
                String nacionalidad = "";
                String genero = "";
                String foto = "";
                String win = "";
                String same = "";
                String lose = "";
                String id = "";
                String nota ="";
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File("./database/animales"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()))) {

                
                
                
                int count =0;
                while ((line = br.readLine()) != null) {
                    if (count==0){
                        nombre=line;
                    }else if (count==1){
                        dia=line;
                    }else if (count==2){
                        mes=line;
                    }else if (count==3){
                        year=line;
                    }else if (count==4){
                        madre=line;
                    }else if (count==5){
                        padre=line;
                    }else if (count==6){
                        nacionalidad=line;
                    }else if (count==7){
                        genero=line;
                    }else if (count==8){
                        foto=line;
                    }else if (count==9){
                        win=line;
                    }else if (count==10){
                        same=line;
                    }else if (count==11){
                        lose=line;
                    }else if (count==12){
                        id=line;
                    }else{
                        nota=nota+line+"\n";
                    }
                    count++;
                }      try {
                    br.close();
                    agregarpelea calc = new agregarpelea();
                    calc.newwindow(nombre, dia, mes, year, madre, padre, nacionalidad, genero, foto, win, same, lose, id,nota);
                    calc.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    
                                               

    }//GEN-LAST:event_addpeleaActionPerformed

    private void profilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesActionPerformed
                String line;
                String nombre = "";
                String dia = "";
                String mes = "";
                String year = "";
                String madre = "";
                String padre = "";
                String nacionalidad = "";
                String genero = "";
                String foto = "";
                String win = "";
                String same = "";
                String lose = "";
                String id = "";
                String nota ="";
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File("./database/animales"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()))) {

                
                
                
                int count =0;
                while ((line = br.readLine()) != null) {
                    if (count==0){
                        nombre=line;
                    }else if (count==1){
                        dia=line;
                    }else if (count==2){
                        mes=line;
                    }else if (count==3){
                        year=line;
                    }else if (count==4){
                        madre=line;
                    }else if (count==5){
                        padre=line;
                    }else if (count==6){
                        nacionalidad=line;
                    }else if (count==7){
                        genero=line;
                    }else if (count==8){
                        foto=line;
                    }else if (count==9){
                        win=line;
                    }else if (count==10){
                        same=line;
                    }else if (count==11){
                        lose=line;
                    }else if (count==12){
                        id=line;
                    }else{
                        nota=nota+line+"\n";
                    }
                    count++;
                }      try {
                    br.close();
                    Profile calc = new Profile();
                    calc.newwindow(nombre, dia, mes, year, madre, padre, nacionalidad, genero, foto, win, same, lose, id,nota);
                    calc.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
} 
        
    }//GEN-LAST:event_profilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpelea;
    private javax.swing.JButton addprofile;
    private javax.swing.JButton editprofile;
    private javax.swing.JButton endprofile;
    private javax.swing.JPanel mainlblpanel;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JButton profiles;
    // End of variables declaration//GEN-END:variables
}
